name: Harison Souza
# permalink: /:title/
# baseurl: https://harisonsouza.com
baseurl: "/MySite"
permalink: /blog/:title

# seo tag
plugins:
  - jekyll-seo-tag

# Google Analytics
google_analytics: G-TEEDE1GB8S

title: Harison Souza
author: Harison Souza
#description: "Software Developer<br> Backend"
description: "Software Developer"

description2: ""

# Caminho para sua foto de perfil (coloque a imagem na pasta /assets/img/)
avatar: /img/avatar.png

# Links das redes sociais
social:
  - name: GitHub
    type: fab  # <-- Adicione essa linha
    icon: fa-github
    url: "https://github.com/harisongsouza"
  - name: YouTube
    type: fab  # <-- Adicione essa linha
    icon: fa-youtube
    url: "https://www.youtube.com/@HarisonGSouza"
  - name: Instagram
    type: fab  # <-- Adicione essa linha
    icon: fa-instagram
    url: "https://www.instagram.com/harisong___/"
  - name: Linkedin
    type: fab  # <-- Note que aqui é 'fas' para o envelope
    icon: fa-linkedin
    url: "https://www.linkedin.com/in/souzaharison/"
  - name: Tiktok
    type: fab  # <-- Note que aqui é 'fas' para o envelope
    icon: fa-tiktok
    url: ""
  - name: Email
    type: fas  # <-- Note que aqui é 'fas' para o envelope
    icon: fa-envelope
    url: "mailto:souzaharison2@gmail.com"
