name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # roda quando fizer push na branch main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # ou outra compatível com seu projeto
          bundler-cache: true

      - name: Instalar dependências
        run: bundle install

      - name: Build do site Jekyll
        run:
